---
title: "Mini-Project 2"
author: "Julianna Alvord and Peyton Draper"
date: "October 31, 2017"
output: html_document
---

#Sequels Using SQL
```{r, include = FALSE}
library(tidyverse)
library(ggplot2)

install.packages("mdsr")
# do NOT install RMySQL if you are on the RStudio Server
install.packages("RMySQL")

library(dplyr)
library(mdsr)
library(RMySQL)
db <- dbConnect_scidb(dbname = "imdb")

#Tables within IMDB database!
dbListTables(db)

#Listing variables in a table!
dbListFields(db, "title")

#Visualizing tables as an example
#movie_link table tells what is a sequel
sql <- "
SELECT *
FROM kind_type
LIMIT 0, 100;
"
type_kind_tb <- db %>%
  dbGetQuery(sql)
View(type_kind_tb)
```

```{r, include = FALSE}
#Example code <- Find your fav movie!
sql <- "
SELECT t.title, t.production_year
FROM title t 
WHERE t.title LIKE '%Stick It%'
  AND t.kind_id = 1
ORDER BY production_year;
"
db %>%
  dbGetQuery(sql)
```

#All of the movies that are made in US each year
```{r}
sql <- "
SELECT count(DISTINCT t.id) as count, production_year
FROM title t
JOIN movie_info mi ON mi.movie_id = t.id
WHERE production_year <= 2017
AND kind_id = 1
AND info_type_id = 8
AND info LIKE '%USA%'
GROUP BY production_year;
"

total_US_movies <- db %>%
  dbGetQuery(sql)
```

#All of the sequels that are made in US each year
```{r}
sql2 <- "
SELECT count(DISTINCT t.id) as count, t.production_year
FROM movie_link m
JOIN title t ON t.id = m.movie_id
JOIN title t2 on t2.id = m.linked_movie_id
JOIN link_type l ON l.id = m.link_type_id
JOIN kind_type k ON k.id = t.kind_id
JOIN movie_info mi ON mi.movie_id = t.id
WHERE k.kind = 'movie'
AND t.production_year <= 2017
AND l.id IN (1, 2, 3, 4, 9, 10, 13)
AND mi.info_type_id = 8
AND info LIKE '%USA%'
GROUP BY t.production_year;
"

sequel_US_movies <- db %>%
  dbGetQuery(sql2)
```

#All of the revenue made by any US movie each year
```{r}
sql3 <- "
SELECT t.id, production_year, substring_index(mi.info, '$', -1) as revenue
FROM movie_info mi
JOIN title t ON t.id = mi.movie_id
WHERE production_year <= 2017
AND kind_id = 1
AND mi.info_type_id = 107
AND mi.info LIKE '%USA%'
AND mi.info NOT Like '%Non-USA%'
AND mi.info NOT LIKE '%Worldwide%';
"

total_US_revenue <- db %>%
  dbGetQuery(sql3)
```

#All of the revenue made by any US sequel each year
```{r}
sql4 <- "
SELECT DISTINCT t.id, t.title, t.production_year, mi.info
FROM movie_link m
JOIN title t ON t.id = m.movie_id
JOIN title t2 on t2.id = m.linked_movie_id
JOIN link_type l ON l.id = m.link_type_id
JOIN kind_type k ON k.id = t.kind_id
JOIN movie_info mi ON mi.movie_id = t.id
WHERE k.kind = 'movie'
AND t.production_year <= 2017
AND l.id IN (1, 2, 3, 4, 9, 10, 13)
AND mi.info_type_id = 107
AND mi.info LIKE '%USA%'
AND mi.info NOT Like '%Non-USA%'
AND mi.info NOT LIKE '%Worldwide%';
"

sequel_US_revenue <- db %>%
  dbGetQuery(sql4)
```